package problems

type problem00002 struct {
	sum float64
}

func (prob problem00002) getInfo() (string, string) {
	return "Even Fibonacci Numbers", "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
}

func (prob *problem00002) solve() {
	prob.sum = 0

	prev := 1
	curr := 2

	for curr < 4000000 {
		if curr%2 == 0 {
			prob.sum += float64(curr)
		}

		next := prev + curr
		prev = curr
		curr = next
	}
}

func (prob problem00002) getExpectedResult() float64 {
	return float64(4613732)
}

func (prob problem00002) getActualResult() float64 {
	return prob.sum
}
